<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1654171755745" stop="1654171755785">
  <name>scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1654171755745" status="failed" stop="1654171755780">
      <name>test_login.TestLogin.test_login_001</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x00000232D26FB240&gt;

    def test_login_001(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:3: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="10500-MainThread"/>
        <label name="host" value="PC-20200119FDVT"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1654171755782" status="passed" stop="1654171755783">
      <name>test_login.TestLogin.test_login_002</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="10500-MainThread"/>
        <label name="host" value="PC-20200119FDVT"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1654171755784" status="passed" stop="1654171755785">
      <name>test_login.TestLogin.test_login_003</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="10500-MainThread"/>
        <label name="host" value="PC-20200119FDVT"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
